controller_manager:
    ros__parameters:
        update_rate: 30
        use_sim_time: true
        
        diff_drive_controller: 
            type: diff_drive_controller/DiffDriveController
            
        joint_state:
            type: joint_state_broadcaster/JointStateBroadcaster
            
            
            
diff_drive_controller:
    ros__parameters:
        publish_rate: 30.0
        
        base_frame_id: base_link
        
        left_wheel_names: ['left_wheel_joint']
        right_wheel_names: ['right_wheel_joint']        
        wheel_separation: 0.25
        wheel_radius: 0.06
        
        use_stamped_vel: true
        
